$ErrorActionPreference = 'Stop'
$env:MPLCONFIGDIR = Join-Path (Get-Location) '.matplotlib'

# Gold retrain from train-only CSV
$env:GOLD_CLEAN_DF_PATH = 'df_gold_dataset_gepu_extended_train.csv'
$env:GOLD_TARGET_COL = 'Gold_Futures'
$env:GOLD_DATE_COL = 'Date'
$env:GOLD_HORIZON = '1'
$env:GOLD_OUTER_TRAIN_RATIO = '0.88'
$env:GOLD_FINAL_VAL_RATIO = '0.12'
$env:GOLD_REPORTS_DIR = 'reports/gold_train_only_retrained'
$env:GOLD_SAVE_ROOT_DIR = 'models/gold_train_only_retrained'
$env:GOLD_INIT_POINTS = '24'
$env:GOLD_N_ITER = '72'
$env:GOLD_MAX_EPOCHS_TUNING = '90'
$env:GOLD_MAX_EPOCHS_FINAL = '110'
$env:GOLD_EARLY_STOPPING_PATIENCE = '8'
$env:GOLD_EARLY_STOPPING_MIN_DELTA = '5e-5'
$env:GOLD_LOOKBACK_RANGE = '18,42'
$env:GOLD_FILTERS_RANGE = '16,64'
$env:GOLD_KERNEL_SIZE_RANGE = '2,4'
$env:GOLD_LSTM_UNITS_RANGE = '32,112'
$env:GOLD_DENSE_UNITS_RANGE = '16,48'
$env:GOLD_DROPOUT_RANGE = '0.18,0.48'
$env:GOLD_LEARNING_RATE_RANGE = '0.0003,0.01'
$env:GOLD_L2_REG_RANGE = '0.00005,0.002'
$env:GOLD_BATCH_SIZE_EXP_RANGE = '4,7'

& .\.venv\Scripts\python.exe train_gold_RRL_interpolate.py

# Silver retrain from train-only CSV
$env:SILVER_CLEAN_DF_PATH = 'silver_RRL_interpolate_extended_train.csv'
$env:SILVER_TARGET_COL = 'Silver_Futures'
$env:SILVER_DATE_COL = 'Date'
$env:SILVER_HORIZON = '1'
$env:SILVER_OUTER_TRAIN_RATIO = '0.88'
$env:SILVER_FINAL_VAL_RATIO = '0.12'
$env:SILVER_REPORTS_DIR = 'reports/silver_train_only_retrained'
$env:SILVER_SAVE_ROOT_DIR = 'models/silver_train_only_retrained'
$env:SILVER_INIT_POINTS = '24'
$env:SILVER_N_ITER = '72'
$env:SILVER_MAX_EPOCHS_TUNING = '90'
$env:SILVER_MAX_EPOCHS_FINAL = '110'
$env:SILVER_EARLY_STOPPING_PATIENCE = '8'
$env:SILVER_EARLY_STOPPING_MIN_DELTA = '5e-5'
$env:SILVER_LOOKBACK_RANGE = '10,28'
$env:SILVER_FILTERS_RANGE = '16,64'
$env:SILVER_KERNEL_SIZE_RANGE = '2,4'
$env:SILVER_LSTM_UNITS_RANGE = '64,160'
$env:SILVER_DENSE_UNITS_RANGE = '16,48'
$env:SILVER_DROPOUT_RANGE = '0.18,0.48'
$env:SILVER_LEARNING_RATE_RANGE = '0.0003,0.008'
$env:SILVER_L2_REG_RANGE = '0.00001,0.0008'
$env:SILVER_BATCH_SIZE_EXP_RANGE = '4,7'

& .\.venv\Scripts\python.exe train_silver_RRL_interpolate.py
